---
- name: Instalar Docker y configurar Jenkins en contenedor Docker
  hosts: jenkins_vm
  become: true

  tasks:
    - name: Instalar Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Iniciar y habilitar servicio Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Descargar imagen oficial de Jenkins LTS
      docker_image:
        name: jenkins/jenkins
        tag: lts
        source: pull

    - name: Ejecutar contenedor Jenkins
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock

    - name: Crear script Groovy para crear usuario admin en VM temporalmente
      copy:
        dest: /tmp/basic-security.groovy
        content: |
          import jenkins.model.*
          import hudson.security.*

          def instance = Jenkins.getInstance()

          def hudsonRealm = new HudsonPrivateSecurityRealm(false)
          hudsonRealm.createAccount("admin", "admin_password")
          instance.setSecurityRealm(hudsonRealm)

          def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
          strategy.setAllowAnonymousRead(false)
          instance.setAuthorizationStrategy(strategy)

          instance.save()

    - name: Crear carpeta init.groovy.d dentro del contenedor Jenkins
      shell: docker exec jenkins mkdir -p /var/jenkins_home/init.groovy.d

    - name: Copiar script Groovy dentro del contenedor Jenkins
      shell: docker cp /tmp/basic-security.groovy jenkins:/var/jenkins_home/init.groovy.d/basic-security.groovy

    - name: Reiniciar contenedor Jenkins para aplicar configuración
      docker_container:
        name: jenkins
        state: started
        recreate: yes

