---
- name: Crear credenciales en Jenkins usando Jenkins CLI
  hosts: jenkins_vm
  become: yes
  gather_facts: no

  vars:
    jenkins_url: http://localhost:8080
    jenkins_admin_user: admin
    jenkins_admin_password: admin_password
    jenkins_cli_jar: /tmp/jenkins-cli.jar

  tasks:
    - name: Instalar OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    ##################################################################
    # Esperar a que Jenkins esté disponible
    ##################################################################
    - name: Esperar a que Jenkins esté disponible
      uri:
        url: "{{ jenkins_url }}/login"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10

    ##################################################################
    # Descargar Jenkins CLI
    ##################################################################
    - name: Descargar jenkins-cli.jar
      get_url:
        url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
        dest: "{{ jenkins_cli_jar }}"

    ##################################################################
    # Crear archivos XML para las credenciales
    ##################################################################
    - name: Crear archivo temporal con XML de Docker Hub credencial
      copy:
        content: |
          <?xml version='1.1' encoding='UTF-8'?>
          <com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
            <scope>GLOBAL</scope>
            <id>dockerhub-cred</id>
            <username>dylalva</username>
            <password>{{ lookup('env', 'DOCKER_PASSWORD') }}</password>
            <description>Docker Hub Credentials</description>
          </com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
        dest: /tmp/dockerhub-cred.xml
        mode: '0644'

    - name: Crear archivo temporal con XML de Azure SP credencial
      copy:
        content: |
          <?xml version='1.1' encoding='UTF-8'?>
          <com.microsoft.azure.credentials.AzureServicePrincipal>
            <scope>GLOBAL</scope>
            <id>azure-service-principal</id>
            <subscriptionId>{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}</subscriptionId>
            <clientId>{{ lookup('env', 'AZURE_CLIENT_ID') }}</clientId>
            <clientSecret>{{ lookup('env', 'AZURE_CLIENT_SECRET') }}</clientSecret>
            <tenant>{{ lookup('env', 'AZURE_TENANT_ID') }}</tenant>
            <description>Azure Service Principal</description>
          </com.microsoft.azure.credentials.AzureServicePrincipal>
        dest: /tmp/azure-sp-cred.xml
        mode: '0644'

    ##################################################################
    # Verificar credenciales existentes
    ##################################################################
    - name: Verificar credenciales existentes
      shell: >
        java -jar {{ jenkins_cli_jar }} -s {{ jenkins_url }}
        -auth {{ jenkins_admin_user }}:{{ jenkins_admin_password }}
        list-credentials system::system::jenkins
      register: existing_credentials
      args:
        executable: /bin/bash
      ignore_errors: yes

    ##################################################################
    # Crear credencial Docker Hub usando Jenkins CLI
    ##################################################################
    - name: Crear credencial Docker Hub usando Jenkins CLI
      shell: >
        java -jar {{ jenkins_cli_jar }} -s {{ jenkins_url }}
        -auth {{ jenkins_admin_user }}:{{ jenkins_admin_password }}
        create-credentials system::system::jenkins < /tmp/dockerhub-cred.xml
      args:
        executable: /bin/bash
      when: "'dockerhub-cred' not in existing_credentials.stdout"
      register: dockerhub_result
      ignore_errors: yes


    ##################################################################
    # Crear credencial Azure Service Principal usando Jenkins CLI
    ##################################################################
    - name: Crear credencial Azure SP usando Jenkins CLI
      shell: >
        java -jar {{ jenkins_cli_jar }} -s {{ jenkins_url }}
        -auth {{ jenkins_admin_user }}:{{ jenkins_admin_password }}
        create-credentials system::system::jenkins < /tmp/azure-sp-cred.xml
      args:
        executable: /bin/bash
      when: "'azure-service-principal' not in existing_credentials.stdout"
      register: azure_result
      ignore_errors: yes

    ##################################################################
    # Verificar que las credenciales se crearon correctamente
    ##################################################################
    - name: Verificar credenciales creadas
      shell: >
        java -jar {{ jenkins_cli_jar }} -s {{ jenkins_url }}
        -auth {{ jenkins_admin_user }}:{{ jenkins_admin_password }}
        list-credentials system::system::jenkins
      register: final_credentials
      args:
        executable: /bin/bash

    - name: Mostrar credenciales existentes
      debug:
        msg: "Credenciales disponibles: {{ final_credentials.stdout_lines }}"

    ##################################################################
    # Limpiar archivos temporales
    ##################################################################
    - name: Limpiar archivos temporales
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ jenkins_cli_jar }}"
        - /tmp/dockerhub-cred.xml
        - /tmp/azure-sp-cred.xml

    ##################################################################
    # Mensaje final de éxito
    ##################################################################
    - name: Credenciales Docker Hub y Azure creadas con éxito 🎉
      debug:
        msg: "✅ Credenciales Docker Hub y Azure Service Principal creadas con éxito."

    - name: Mostrar resultados de creación
      debug:
        msg: |
          Resultado Docker Hub: {{ dockerhub_result.stdout | default('No ejecutado') }}
          Resultado Azure: {{ azure_result.stdout | default('No ejecutado') }}