name: Provision AKS Cluster and Install Cert-Manager

on:
  workflow_dispatch:

jobs:
  deploy_aks_and_certmanager:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./infrastructurek8s
        run: terraform init

      - name: Terraform Apply - Create AKS Cluster
        working-directory: ./infrastructurek8s
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -auto-approve

      - name: Azure Login & Get AKS credentials
        uses: azure/login@v1
        with:
          creds: >
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Get AKS kubeconfig
        run: |
          az aks get-credentials --resource-group k8spruebas --name PRUEBAS --overwrite-existing

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install Cert-Manager with Ansible
        run: |
          ansible-playbook -i localhost, --connection=local ./infrastructurek8s/cert-manager-setup.yml
