name: Configurar Jenkins completo en Docker

on:
  workflow_dispatch:

jobs:
  setup_jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Instalar Ansible y herramientas necesarias
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass curl openjdk-11-jdk

      - name: Ejecutar playbook para configurar Jenkins
        run: |
          ansible-playbook -i infrastructure/hosts.ini infrastructure/jenkins-install.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
