name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACK_SECRET }}

    - name: Build Docker image
      run: |
        # Convert owner and repo to lowercase
        OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
        REPO=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG="ghcr.io/$OWNER/$REPO:latest"
        echo "Building image $IMAGE_TAG"
        docker build -t $IMAGE_TAG .

    - name: Push Docker image
      run: |
        OWNER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
        REPO=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG="ghcr.io/$OWNER/$REPO:latest"
        echo "Pushing image $IMAGE_TAG"
        docker push $IMAGE_TAG
